- hosts: consul
  become: yes
  gather_facts: false
  roles:
    - env_init/system/firewalld
    - env_init/system/selinux
    - env_init/system/sysctl
    - env_init/system/ulimit
    - env_init/createuser
    - env_init/createdir
    - env_init/jdk
    - env_init/python-virtualenv
    - env_init/modify_resolv.conf
  tags:
    - env_init


- hosts: consul
  become: yes
  gather_facts: false
  roles:
    - consul
  tags:
    - consul
